
@url = http://localhost:3000

### Verifica se a API está respondendo
GET {{url}}/tarefas


### Busca uma tarefa específica por ID
GET {{url}}/tarefas/1


### Criando uma nova tarefa
POST {{url}}/tarefas
Content-Type: application/json

{
  "titulo": "Comprar pão",
  "descricao": "Fazer compras no mercado"
}


### Atualizando parcialmente uma tarefa (PATCH)
PATCH {{url}}/tarefas/1
Content-Type: application/json

{
  "titulo": "Comprar pão atualizado",
  "descricao": "Compras no supermercado"
}


### Alternar o status da tarefa de ID 1 para concluída
PATCH {{url}}/tarefas/1/concluir


### Excluindo uma tarefa
DELETE {{url}}/tarefas/1


### Forçando erro 404 no NotFoundHandler
GET {{url}}/batata-frita